/**
 * ERDL MCP Server — Coding Preset Rules (Tool Call Guard mode)
 *
 * Rules match against tool_name + tool_args, per ERDL Spec §5.3.
 *
 * @author 唐浩然 (Tang Haoran) · OpenOBA AI 执行官
 * @since 2026-07-08
 * @license MIT
 */

import type { RuleDefinition } from '../../engine/rule-definition.js'

/** Common coding tool names these rules apply to */
const CODING_TOOLS = ['write_file', 'edit', 'apply_patch', 'exec', 'write']

export const codingRules: RuleDefinition[] = [
  {
    id: 'CD-001',
    name: 'no_any',
    description: 'Never use `any` in TypeScript.',
    category: 'coding',
    triggers: ['write_file', 'edit', 'apply_patch'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'in', value: CODING_TOOLS }],
    action: { decision: 'ALLOW', instruction: 'Do NOT use `any` type. Use `unknown` with type guards, define a proper type/interface, or use generics.' },
    priority: 5,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-002',
    name: 'no_ts_ignore',
    description: 'Never suppress TypeScript errors without reason.',
    category: 'coding',
    triggers: ['write_file', 'edit', 'apply_patch'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'in', value: CODING_TOOLS }],
    action: { decision: 'ALLOW', instruction: 'Do NOT use @ts-ignore/@ts-expect-error without a comment explaining why.' },
    priority: 5,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-003',
    name: 'naming_conventions',
    description: 'camelCase for vars/functions, PascalCase for classes, UPPER_SNAKE for constants.',
    category: 'coding',
    triggers: ['write_file', 'edit', 'apply_patch'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'in', value: CODING_TOOLS }],
    action: { decision: 'ALLOW', instruction: 'Use camelCase, PascalCase, UPPER_SNAKE_CASE as appropriate.' },
    priority: 10,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-004',
    name: 'handle_promises',
    description: 'Promise must be awaited or .catch()',
    category: 'coding',
    triggers: ['write_file', 'edit', 'apply_patch'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'in', value: CODING_TOOLS }],
    action: { decision: 'ALLOW', instruction: 'Every Promise must be awaited or have .catch() handler.' },
    priority: 5,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-005',
    name: 'no_nested_ternary',
    description: 'No nested ternary expressions.',
    category: 'coding',
    triggers: ['write_file', 'edit', 'apply_patch'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'in', value: CODING_TOOLS }],
    action: { decision: 'ALLOW', instruction: 'No nested ternary. Use if-else or switch.' },
    priority: 20,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-006',
    name: 'commit_format',
    description: 'Commit with type(scope): description format.',
    category: 'coding',
    triggers: ['exec'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'eq', value: 'exec' }],
    action: { decision: 'ALLOW', instruction: 'Commit format: type(scope): description. E.g., feat(api): add user endpoint.' },
    priority: 5,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-007',
    name: 'one_commit_one_change',
    description: 'One commit per logical change.',
    category: 'coding',
    triggers: ['exec'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'eq', value: 'exec' }],
    action: { decision: 'ALLOW', instruction: 'One commit = one logical change. Separate concerns into distinct commits.' },
    priority: 10,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-008',
    name: 'pr_emoji',
    description: 'PR title with emoji prefix.',
    category: 'coding',
    triggers: ['write_file', 'edit'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'in', value: CODING_TOOLS }],
    action: { decision: 'ALLOW', instruction: 'PR title should start with emoji prefix: ✨ feat, 🐛 fix, 📖 docs, ♻️ refactor, etc.' },
    priority: 15,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-009',
    name: 'confirm_dependencies',
    description: 'New dependencies must be confirmed with Henry first.',
    category: 'coding',
    triggers: ['write_file', 'edit', 'exec'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'in', value: CODING_TOOLS }],
    action: { decision: 'REQUEST_HUMAN', reason: 'New dependencies must be confirmed with Henry before adding.' },
    priority: 3,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
  {
    id: 'CD-010',
    name: 'prefer_existing',
    description: 'Prefer existing dependencies over adding new ones.',
    category: 'coding',
    triggers: ['write_file', 'edit', 'exec'],
    conditions: [{ kind: 'context_matches', field: 'tool.name', operator: 'in', value: CODING_TOOLS }],
    action: { decision: 'ALLOW', instruction: 'Check existing dependencies before adding new ones. Reuse what is already installed.' },
    priority: 5,
    enabled: true,
    version: 1,
    hitCount: 0,
  },
]
